pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-south-1'
        IMAGE_NAME = 'snapshot-cleaner'
    }
    stages {
        stage('Build') {
            steps {
                dir('docker') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'python3 -m unittest lambda/test_snapshots.py'
            }
        }
        stage('Deploy') {
            steps {
                withAWS(credentials: 'aws-credentials') {
                    sh 'aws lambda update-function-code --function-name snapshot_cleaner --zip-file fileb://docker/lambda.zip'
                }
            }
        }
    }
}